databases:
  - name: oshi_task_db
    databaseName: oshi_task_db
    user: oshi_task-1
    region: singapore

services:
  - type: web
    name: oshi_task-1
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oshi_task_db-1
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false